#!/bin/sh

cutdir=${cutdir-..}
bindir=${cutdir}/bin/
inputsdir=${cutdir}/inputs/
resultsdir=${cutdir}/results/
suffix=`basename $0`

rm -f ${resultsdir}$1.$suffix
touch ${resultsdir}$1.$suffix

for n in 16384 32768 65536 131072 262144 
do
  for seed in `awk "BEGIN {s=31401; for(i=0; i<${cutnumseeds-1};i++) {s+=10; print s}}"`
  do
    for rseed in `awk "BEGIN {s=1401; for(i=0; i<${cutnumrandseeds-1};i++) {s+=10; print s}}"`
    do
      echo "${bindir}cyclegen $n -U${n}00 -s$seed | ${bindir}$1 -s$rseed >>${resultsdir}$1.$suffix"
      ${bindir}cyclegen $n -U${n}00 -s$seed | ${bindir}$1 -s$rseed >> ${resultsdir}$1.$suffix
    done
  done
done

